#############################
# Xups for Hexo 主题配置文件
# Jelon
# http://jelon.info
#############################

#----------------------------
# 头部导航
#----------------------------
menu:
  home:
    name: 首页
    link: /
    icon: icon-home
  archives:
    name: 归档
    link: /archives/
    icon: icon-archives
  about:
    name: 关于
    link: /about/
    icon: icon-staff
#  comment:
#    name: 留言
#    link: /comment/
#    icon: icon-comment

#----------------------------
# 副导航
#----------------------------
subnav:
  github: "#"
  weibo: "#"
  rss: "#"
  zhihu: "#"

#----------------------------
# RSS
#----------------------------
rss: /atom.xml

#----------------------------
# Favicon
#----------------------------
favicon: /favicon.png

#----------------------------
# 头像url
#----------------------------
avatar: /img/avatar.jpg

#----------------------------
# 是否开启分享
#----------------------------
share: true

#----------------------------
# 侧栏是否显示微博秀
#----------------------------
weibo_show:
  enable: false
  code: <iframe id="myWeibo" width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=2376003112&verifier=796ea597&dpc=1"></iframe>

#----------------------------
# 是否开启评论
#----------------------------
comment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:

#----------------------------
# 是否开启云标签
#----------------------------
tagcloud: true

#----------------------------
# 友情链接
#----------------------------
friends:
  enable: false
  list:
    1:
      name: Github博客
      title: Github博客
      link: https://github.com/front-end-pigs/blog
    2:
      name: Jelon博客
      title: Jelon博客
      link: https://jelon.info
#----------------------------
# 头部链接
#----------------------------
head_links:
  enable: false
  list:
    sup:
      0:
        name: Github
        link: https://github.com/zhweif
      last:
        name: Hosted by Coding Pages
        link: https://pages.coding.me
    sub:
      sinaweibo:
        name: 新浪微博
        link: http://weibo.com/jangdelong
      qqweibo:
        name: 掘金
        link: https://juejin.im/user/3984285869282919
#----------------------------
# SEO
#----------------------------
SEO:
  keywords: 锋哥, 后端, Web, 张伟锋, 后端开发
  description: 个人博客

#----------------------------
# 百度分析
#----------------------------
baidu_analytics:
  enbale: false
  analytics_url:

#----------------------------
# 高亮样式
#----------------------------
highlight_theme: normal
#----------------------------
# CDN
# 如: //7xs305.com1.z0.glb.clouddn.com/
# 主要以下两个目录进行 cdn 存储
#   - img 图片资源下的 thumbnail 目录
#   - css 样式资源下的 fonts 目录
#----------------------------
CDN:

#----------------------------
# 是否开启搜索
#----------------------------
search:
  enable: true
  placeholder: 输入关键字搜索

#----------------------------
# 是否全栈致灰
#----------------------------
is_site_grey: false
